// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DevelopmentFirebaseOptions.currentPlatform,
/// );
/// ```
class DevelopmentFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DevelopmentFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DevelopmentFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDVgVwh-EfyXpRxT7sdNKWxQBOzrNRFRM',
    appId: '1:835576059374:web:dd2c9a784388f436822aff',
    messagingSenderId: '835576059374',
    projectId: 'ota-management-platform',
    authDomain: 'ota-management-platform.firebaseapp.com',
    storageBucket: 'ota-management-platform.firebasestorage.app',
    measurementId: 'G-CLNTZZYD0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg5pE2Q6rn-RGW1RoV5EJ1NS1PufDzTr0',
    appId: '1:835576059374:android:abd14d2a4564a748822aff',
    messagingSenderId: '835576059374',
    projectId: 'ota-management-platform',
    storageBucket: 'ota-management-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_tH-fwVrwcerkr0X8-hgaxV0TeXwE5ao',
    appId: '1:835576059374:ios:6c88cf13dca65a37822aff',
    messagingSenderId: '835576059374',
    projectId: 'ota-management-platform',
    storageBucket: 'ota-management-platform.firebasestorage.app',
    iosBundleId: 'com.example.otaCheshireManagementPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_tH-fwVrwcerkr0X8-hgaxV0TeXwE5ao',
    appId: '1:835576059374:ios:6c88cf13dca65a37822aff',
    messagingSenderId: '835576059374',
    projectId: 'ota-management-platform',
    storageBucket: 'ota-management-platform.firebasestorage.app',
    iosBundleId: 'com.example.otaCheshireManagementPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDVgVwh-EfyXpRxT7sdNKWxQBOzrNRFRM',
    appId: '1:835576059374:web:3bad5d73893465d2822aff',
    messagingSenderId: '835576059374',
    projectId: 'ota-management-platform',
    authDomain: 'ota-management-platform.firebaseapp.com',
    storageBucket: 'ota-management-platform.firebasestorage.app',
    measurementId: 'G-C94S7Y2ERW',
  );
}
