abstract final class OtaRoutes {
  static const gate = '/';
  static const welcome = '/welcome';
  static const dashboard = '/dashboard';
  static const schedule = '/schedule';
  static const events = '/events';
  static const resources = '/resources';
  static const generalResources = '/resources/general';
  static const curriculum = '/curriculum';
  static const notifications = '/notifications';
  static const profile = '/profile';
  static const manageProfiles = '/profile/manage';
  static const login = '/login';
  static const signup = '/signup';
  static const adminDashboard = '/admin/dashboard';
  static const adminStudents = '/admin/students';
  static const adminEvents = '/admin/events';
  static const adminAnnouncements = '/admin/announcements';
  static const adminSchedule = '/admin/schedule';
  static const adminResources = '/admin/resources';
  static const adminGeneralResources = '/admin/resources/general';
  static const adminCurriculum = '/admin/resources/curriculum';
  static const adminProfile = '/admin/profile';
}
