name: Build Debug APK Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-apk-release:
    name: Build and Release Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug --flavor dev -t lib/main_dev.dart

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-dev-debug.apk OTA-Cheshire-debug.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: apk-${{ github.run_number }}
          name: Debug APK ${{ github.run_number }}
          files: OTA-Cheshire-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
